language: c

os:
  - linux
  - osx
  
env:
 - CABALVER=1.22 GHCVER=7.10.2
 
services:
  - docker
 
install:     
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install idris; fi
  
    
script:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then docker build -t idris-minesweeper .; fi
    
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then idris --version; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then idris --build minesweeper.ipkg; fi
